spring:
  profiles:
    active: develop
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:~/trading-bot/db
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  flyway:
    user: sa
    password: pass

logging:
  level:
    org.springframework: warn
    com.faystmax: info
    root: warn

telegram:
  proxy:
    port: 1080
    host: 51.83.2.136
    type: SOCKS5