spring:
  profiles:
    active: develop
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: Europe/Moscow
    date-format: dd.MM.yyyy HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
  datasource:
    url: jdbc:h2:file:~/trading-bot/db
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  flyway:
    user: sa
    password: pass

server:
  port: 8090
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: warn
    com.faystmax: info
    root: warn

telegram:
  proxy:
    port: 1080
    host: 96.113.176.101
    type: SOCKS5