server:
  port: 8090
  shutdown: graceful

spring:
  profiles:
    active: develop
  jackson:
    time-zone: Europe/Moscow
    date-format: dd.MM.yyyy HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_bot
    username: trading_bot
    password: password

logging:
  level:
    com.faystmax: info
    root: warn

jwt:
  secret: client_secret
  expiration: 604800000 # one week

cors:
  allowOrigin: http://localhost:3000

binance:
  base-commission: 0.0001