spring:
  profiles:
    active: develop
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: Europe/Moscow
    date-format: dd.MM.yyyy HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
  datasource:
    url: jdbc:h2:file:~/trading-bot/db
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  flyway:
    user: sa
    password: pass
  mvc:
    locale: en_US

server:
  port: 8090

logging:
  level:
    org.springframework: warn
    com.faystmax: info
    root: warn

jwt:
  secret: client_secret
  expiration: 86400000