ALTER TABLE USER
    ADD COLUMN telegramChatId LONG;

ALTER TABLE USER
    ADD COLUMN tradingSymbol VARCHAR(20);

ALTER TABLE USER
    ADD COLUMN binanceApiKey VARCHAR(200);

ALTER TABLE USER
    ADD COLUMN binanceSecretKey VARCHAR(200);