ALTER TABLE USER
    ADD COLUMN email_host VARCHAR(50);

ALTER TABLE USER
    ADD COLUMN email_username VARCHAR(50);

ALTER TABLE USER
    ADD COLUMN email_password VARCHAR(50);

ALTER TABLE USER
    ADD COLUMN email_folder VARCHAR(50);