ALTER TABLE USER
    ADD COLUMN telegram_chat_id LONG;

ALTER TABLE USER
    ADD COLUMN trading_symbol VARCHAR(20);

ALTER TABLE USER
    ADD COLUMN binance_api_key VARCHAR(200);

ALTER TABLE USER
    ADD COLUMN binance_secret_key VARCHAR(200);