version: "3.5"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=${ELK_PASSWORD}
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline:ro
      - ${LOGS_PATH}:/var/log/trading-bot:ro
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELK_PASSWORD}
    restart: on-failure
    depends_on:
      - elasticsearch