name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew -Pprofile=develop clean build